# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'momsnagging_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for momsnagging_ios
	#UI&CodeConvention
	pod 'SnapKit'
	pod 'Then'
	pod 'Kingfisher'
	pod 'SwiftLint'
	pod 'SwiftGen'
	pod 'Toast-Swift'

	#Networking
	pod 'Moya/RxSwift'
	pod 'SwiftyJSON'

	#async
	pod 'RxSwift'
	pod 'RxCocoa'

	#RX Extensions
	pod 'RxGesture'
	pod 'RxDataSources'
	pod 'RxViewController'
	pod 'RxOptional'
	pod 'RxSwiftExt'
	pod 'RxKeyboard'

	#firebase
	pod 'Firebase/Analytics'
	pod 'Firebase/Crashlytics'
	pod 'Firebase/Messaging'
	pod 'Firebase/AppDistribution'
	pod 'Firebase/RemoteConfig'
  
	#Google
	pod 'GoogleSignIn'
  
	#Kakao
	pod 'RxKakaoSDKAuth'
	pod 'RxKakaoSDKUser'
  
	#Keychain
	pod 'SwiftKeychainWrapper'

  target 'momsnagging_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'momsnagging_iosUITests' do
    # Pods for testing
  end

end
